services:
  frontend:
    restart: never # frontend should not restart, since it's a one-time build cycle.
    build: ./frontend
    volumes:
      # built frontend files will go in /docker/frontend/public
      # so we make a volume to share that with the nginx server
      - built_frontend:/docker/frontend/public 
  backend:
    restart: always
    build: ./backend
    command: "./example_backend"
    depends_on: 
      - db
    expose:
      - "$PORT" # expose backend to nginx
    environment:
      # "- ENV_VAR" is syntactic sugar for "- ENV_VAR=$ENV_VAR"
      - PORT
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
      # this refers to the 'db' service
      - DB_HOST=db
  db:
    restart: always
    image: mariadb
    environment:
      - MARIADB_USER=example_user
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_DATABASE=example_db
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    expose:
      - "3306" # expose db to backend
    volumes:
      # the db creation files
      - ./mariadb/init:/docker-entrypoint-initdb.d
      # in order to preserve data between restarts, a named volume that points to /var/lib/mysql is created
      - mysql_data:/var/lib/mysql
  nginx:
    image: nginx
    restart: always
    environment:
      - BACKEND_PORT=$PORT
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - built_frontend:/usr/share/nginx/frontend
      - ./nginx/templates:/etc/nginx/templates
volumes:
  built_frontend:
  mysql_data:
