services:
  frontend:
    restart: unless-stopped
    build: ./frontend
    expose:
      - 8080 # since we configured frontend port to be 8080 in frontend/Dockerfile
  backend:
    restart: unless-stopped
    build: ./backend
    depends_on: 
      - db
    expose:
      - 8080 # since we configured port to be 8080 in backend/src/main.go
    environment:
      # "- ENV_VAR" is syntactic sugar for "- ENV_VAR=$ENV_VAR"
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
      # this refers to the 'db' service
      - DB_HOST=db
  db:
    restart: unless-stopped
    image: mariadb
    environment:
      - MARIADB_USER=example_user
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_DATABASE=example_db
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    expose:
      - "3306" # expose db to backend
    volumes:
      # the db creation files
      - ./mariadb/init:/docker-entrypoint-initdb.d
      # in order to preserve data between restarts, a named volume that points to /var/lib/mysql is created
      - mysql_data:/var/lib/mysql
  nginx:
    image: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/templates:/etc/nginx/templates
volumes:
  mysql_data:
