services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - frontend_static:/docker/frontend/public
  backend:
    container_name: backend
    build: ./backend
    command: "./example_backend"
    depends_on: 
      - db
    expose:
      - "$PORT" # expose backend to nginx
    environment:
      # "- ENV_VAR" is syntactic sugar for "- ENV_VAR=$ENV_VAR"
      - PORT
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
      # this refers to the 'db' service
      - DB_HOST=db
  db:
    container_name: db
    image: mariadb
    environment:
      - MARIADB_USER=example_user
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_DATABASE=example_db
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    expose:
      - "3306" # expose db to backend
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d # the db creation files
  nginx:
    image: nginx
    container_name: nginx
    environment:
      - BACKEND_PORT=$PORT
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - frontend_static:/usr/share/nginx/frontend
      - ./nginx/templates:/etc/nginx/templates
volumes:
  frontend_static:
